modification

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -60,7 +60,7 @@ jobs:
         id: Tflint-run
         run: tflint --init  && tflint --module
         continue-on-error: false
-      - name: Run tfsec
+      - name: Run-tfsec
         uses: tfsec/tfsec-sarif-action@9a83b5c3524f825c020e356335855741fd02745f
         with:
           working_directory: .
@@ -70,6 +70,18 @@ jobs:
         with:
           # Path to SARIF file relative to the root of the repository
           sarif_file: tfsec.sarif
+      - name: Check tfsec return codes
+        if: success() || failure ()
+        run: |
+          tfsec_return="${{ steps.Run-tfsec.outputs.tfsec-return-code }}"
+         
+          if [[ "$tfsec_return" -eq 1 ]]; then
+            echo "tfsec correctly returned failure ${tfsec_return}"
+            exit 1
+          else
+            echo "tfsec returned ${tfsec_return}, expected '1'. Failing..."
+            exit 0
+          fi
       - name: OPA Install
         id: install 
         run: curl -L -o opa https://openpolicyagent.org/downloads/v0.31.0/opa_linux_amd64_static && chmod 755 opa && sudo mv opa /usr/bin
