test notification

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -146,23 +146,23 @@ jobs:
         # test the OPA rules in .rego files againt the terrform plan.
       - name: OPA Test
         id: opatest
-        run:  opa eval --fail-defined  --format pretty  -d opa-policies/aws/ --input opa-plan1.json "data.terraform.deny"  
+        run:  opa eval  --format pretty  -d opa-policies/aws/ --input opa-plan1.json "data.terraform.deny"  
         continue-on-error: false
         # issues error and stop the job if error occured during OPA check.
-      # - name: Check opa return codes
-      #   if: success() 
-      #   run: |
-      #       opa_return=$(opa eval  --format pretty  -d opa-policies/aws/ --input opa-plan1.json "count(data.terraform.deny)")
-      #        exit $opa_return
-      #   continue-on-error: false
+      - name: Check opa return codes
+        if: success() 
+        run: |
+            opa_return=$(opa eval  --format pretty  -d opa-policies/aws/ --input opa-plan1.json "count(data.terraform.deny)")
+             exit $opa_return
+        continue-on-error: false
       - name: Microsoft Teams Notification
         uses: skitionek/notify-microsoft-teams@master
         if: failure()
         with:
           webhook_url: ${{secrets.MS_TEAMS_WEBHOOK_URI}}
           needs: ${{ toJson(needs) }}
-          job: ${{ toJson(job) }}
-          steps: ${{ toJson(steps) }}      
+          job: ${{ toJson(job) }} 
+  
   Terraform_Plan_Apply:
     runs-on: ubuntu-latest
     needs: ['Tranform_Format','Validate_Syntax_Semantics','Tfsec_job','Validate_OPA']
@@ -204,20 +204,20 @@ jobs:
   #         needs: ${{ toJson(needs) }}
   #         job: ${{ toJson(job) }}
   #         steps: ${{ toJson(steps) }}      
-  Send_notification:
-    runs-on: ubuntu-latest
-    if: failure()
-    needs: ['Tranform_Format','Validate_Syntax_Semantics','Tfsec_job','Validate_OPA','Terraform_Plan_Apply']
-    steps:
-      - uses: actions/checkout@master
-      - name: Microsoft Teams Notification
-        uses: skitionek/notify-microsoft-teams@master
-        if: success()
-        with:
-          webhook_url: ${{secrets.MS_TEAMS_WEBHOOK_URI}}
-          needs: ${{ toJson(needs) }}
-          job: ${{ toJson(job) }}
-          steps: ${{ toJson(steps) }}      
+  # Send_notification:
+  #   runs-on: ubuntu-latest
+  #   if: failure()
+  #   needs: ['Tranform_Format','Validate_Syntax_Semantics','Tfsec_job','Validate_OPA','Terraform_Plan_Apply']
+  #   steps:
+  #     - uses: actions/checkout@master
+  #     - name: Microsoft Teams Notification
+  #       uses: skitionek/notify-microsoft-teams@master
+  #       if: success()
+  #       with:
+  #         webhook_url: ${{secrets.MS_TEAMS_WEBHOOK_URI}}
+  #         needs: ${{ toJson(needs) }}
+  #         job: ${{ toJson(job) }}
+  #         steps: ${{ toJson(steps) }}      
 
     
 
